fix: github actions, setup, and move lighting tools to their own module to avoid circular import (#89)
When running tests, we'd get this:
```
tests/control/test_microscope.py:1: in <module>
    import control.microscope
control/microscope.py:7: in <module>
    import control.core.core as core
control/core/core.py:28: in <module>
    import control.serial_peripherals as serial_peripherals
control/serial_peripherals.py:6: in <module>
    from control.microscope import LightSourceType, IntensityControlMode, ShutterControlMode
E   ImportError: cannot import name 'LightSourceType' from partially initialized module 'control.microscope' (most likely due to a circular import) (/home/ian/projects/cephla/squid/software/control/microscope.py)
```

To fix this, move all the `IlluminationController` machinery to its own
module.

This also fixes our setup mechanism so tests pass.

Tested by: Unit tests run and pass now, and a local gui sim starts.